const normalizeSettingsPayload = (data = {}) => ({
  organizationName: data.organizationName || "",
  shortName: data.shortName || "",
  email: data.email || "",
  phone: data.phone || "",
  address: data.address || "",
  website: data.website || "",
  logo: data.logo || "",
  favicon: data.favicon || "",
  heroImage: data.heroImage || "",
  aboutImage: data.aboutImage || "",
  heroTitle: data.heroTitle || "",
  heroSubtitle: data.heroSubtitle || "",
  aboutTitle: data.aboutTitle || "",
  aboutText: data.aboutText || "",
  storyTitle: data.storyTitle || "",
  storySubtitle: data.storySubtitle || "",
  storyVideoOne: data.storyVideoOne || "",
  storyVideoTwo: data.storyVideoTwo || "",
  storyVideoThree: data.storyVideoThree || "",
  mission: data.mission || "",
  vision: data.vision || "",
  facebook: data.facebook || "",
  linkedin: data.linkedin || "",
  twitter: data.twitter || "",
  instagram: data.instagram || "",
  youtube: data.youtube || "",
  footerText: data.footerText || "",
  projectsCompleted: data.projectsCompleted ?? "",
  livesImpacted: data.livesImpacted ?? "",
  communitiesReached: data.communitiesReached ?? "",
  activeVolunteers: data.activeVolunteers ?? "",
  yearsOfExperience: data.yearsOfExperience ?? "",
  evidenceBasedText: data.evidenceBasedText ?? "",
});

module.exports = {
  normalizeSettingsPayload,
};
